soulbound:
  name: "&7Связь Души"
  biomes:
    - "SOUL_SAND_VALLEY"
  chance: 0.55
  luck: 0
  maxlvl: 1
shockwave:
  name: "&7Тяжелая стрела"
  biomes:
    - "STONY_SHORE"
  chance: 2
  luck: 2
  maxlvl: 4
fireworks:
  name: "&7Пороховой заряд"
  biomes:
    - "BADLANDS"
  chance: 2
  luck: 2
  maxlvl: 3
potioness:
  name: "&7Отравленность"
  biomes:
    - "SPARSE_JUNGLE"
  chance: 3
  luck: 2
  maxlvl: 4
dodge:
  name: "&7Уклонение"
  biomes:
    - "CHERRY_GROVE"
  chance: 1
  luck: 2
  maxlvl: 1
rain:
  name: "&7Шквал Стрел"
  biomes:
    - "WOODED_BADLANDS"
  chance: 1
  luck: 2
  maxlvl: 5
exp:
  name: "&7Образование"
  biomes:
    - "JAGGED_PEAKS"
  chance: 0.4
  luck: 0
  maxlvl: 5
bamboom:
  name: "&7Звуковой заряд"
  biomes:
    - "DEEP_DARK"
  chance: 1
  luck: 3
  maxlvl: 3
tntanon:
  name: "&7Взрывной заряд"
  biomes:
    - "THE_VOID"
  chance: 0
  luck: 0
  maxlvl: 1
fish:
  name: "&7Рыбный заряд"
  biomes:
    - "BEACH"
  chance: 2
  luck: 3
  maxlvl: 1
poshot:
  name: "&7Зельестрел"
  biomes:
    - "THE_VOID"
  chance: 0
  luck: 0
  maxlvl: 1
steveoshot:
  name: "&7Стиво-стрел"
  biomes:
    - "DESERT"
  chance: 0.45
  luck: 0
  maxlvl: 1
antiholy:
  name: "&6Освещённость"
  biomes:
    - "PALE_GARDEN"
  chance: 0.01
  luck: 0
  maxlvl: 1
neverended:
  name: "&7Бескончаемость"
  biomes:
    - "THE_VOID"
  chance: 0
  luck: 0
  maxlvl: 1
democracy:
  name: "&7Нормальность"
  biomes:
    - "THE_END"
  chance: 30
  luck: 0
  maxlvl: 1
telepathy:
  name: "&7Сбор"
  biomes:
    - "SHATTERED_SAVANNA"
  chance: 0.5
  luck: 0
  maxlvl: 1
headless:
  name: "&7Головорез"
  biomes:
    - "END_HIGHLANDS"
  chance: 0.5
  luck: 0
  maxlvl: 1
axicia:
  name: "&7Связь пустоты"
  biomes:
    - "WARPED_FOREST"
  chance: 0.4
  luck: 0
  maxlvl: 1
log:
  name: "&7Быстроруб"
  biomes:
    - "CRIMSON_FOREST"
  chance: 0.25
  luck: 0
  maxlvl: 1
breakerorisit:
  name: "&7Рудолом"
  biomes:
    - "BASALT_DELTAS"
  chance: 2
  luck: 1
  maxlvl: 1
stunning:
  name: "&7Оглушающий удар"
  biomes:
    - "FROZEN_PEAKS"
  chance: 0.08
  luck: 0.4
  maxlvl: 3
myolner:
  name: "&7Искромётность"
  biomes:
    - "DEEP_COLD_OCEAN"
  chance: 0.5
  luck: 0.05
  maxlvl: 5
